name: BetonQuestAddon
version: '${version}'
author: mrjimin
website: https://modrinth.com/plugin/betonquestaddon
description: Extends BetonQuest with additional powerful features.

api-version: "1.21"

main: com.github.mrjimin.betonquestaddon.BetonQuestAddonPlugin
loader: com.github.mrjimin.betonquestaddon.BetonQuestAddonLoader

dependencies:
  server:
    BetonQuest:
      load: BEFORE
      required: true

    ItemsAdder:
      load: BEFORE
      required: false
    Nexo:
      load: BEFORE
      required: false
    CraftEngine:
      load: BEFORE
      required: false
    CustomCrops:
      load: BEFORE
      required: false
    CustomFishing:
      load: BEFORE
      required: false
    CustomNameplates:
      load: BEFORE
      required: false