name: BetonQuestAddon
main: com.github.mrjimin.betonquestaddon.BetonQuestAddonPlugin
version: '${version}'
api-version: 1.20
author: MrJimin
depend:
  - BetonQuest
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.20