[versions]
project_version = "1.3.1"
config_version = "8"
kotlin = "2.3.21"
shadow = "9.2.2"
hangar-publish = "0.1.4"
plugin-yml = "0.9.0"

paper = "1.21.8"
paper-version-range = "1.21.x"
beton-quest = "3.0.0-SNAPSHOT"

nexo = "1.21.0"
items-adder = "4.0.10"
craft-engine = "26.5"
custom-crops = "3.6.40"
custom-fishing = "2.3.23.1"
custom-nameplates = "3.0.19"
hmc-cosmetics = "2.8.3-e88b8461"
world-guard = "7.0.14"
excellent-economy = "2.8.0"

boosted-yaml = "1.3.7"
bstats = "3.1.0"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
betonquest = { group = "org.betonquest", name = "betonquest", version.ref = "beton-quest" }

nexo = { group = "com.nexomc", name = "nexo", version.ref = "nexo" }
itemsadder = { group = "dev.lone", name = "api-itemsadder", version.ref = "items-adder" }
craft-engine-core = { group = "net.momirealms", name = "craft-engine-core", version.ref = "craft-engine" }
craft-engine-bukkit = { group = "net.momirealms", name = "craft-engine-bukkit", version.ref = "craft-engine" }
custom-crops = { group = "net.momirealms", name = "custom-crops", version.ref = "custom-crops" }
custom-fishing = { group = "net.momirealms", name = "custom-fishing", version.ref = "custom-fishing" }
custom-nameplates = { group = "net.momirealms", name = "custom-nameplates", version.ref = "custom-nameplates" }
hmc-cosmetics = { group = "com.hibiscusmc", name = "HMCCosmetics", version.ref = "hmc-cosmetics" }
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref = "world-guard" }
excellent-economy = { group = "su.nightexpress.excellenteconomy", name = "ExcellentEconomy", version.ref = "excellent-economy" }
ae-api = { group = "gg.aquatic", name = "AEAPI", version = "1.0" }

boosted-yaml = { group = "dev.dejvokep", name = "boosted-yaml", version.ref = "boosted-yaml" }
bstats = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
hangar-publish = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar-publish" }
paper-plugin-yml = { id = "de.eldoria.plugin-yml.paper", version.ref = "plugin-yml" }